#!/usr/bin/env python3
# vim: ft=python tabstop=8 expandtab shiftwidth=4 softtabstop=4
import sys,os
# Checks the status of SSH on a machine
# Requires nmap and grep

def main():
    host = sys.argv[1]
    ret = os.system('nmap ' + host + ' -PN -p ssh | grep open > /dev/null')
    if ret !=0:
        #print('SSH is down!')
        sys.exit(1)

main()
